export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED= 'FETCH_WEATHER_FAILED';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const CONVERT_TEMP_TO_FAHRENHEIT = 'CONVERT_TEMP_TO_FAHRENHEIT';
export const CONVERT_TEMP_TO_CELSIUS = 'CONVERT_TEMP_TO_CELSIUS';