export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILED= 'GET_WEATHER_FAILED';
export const GET_LOCATION_FAILED = 'GET_LOCATION_FAILED';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';